version: '3'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9007:9100
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M

  dex:
    image: spx01/dex
    container_name: dex
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9006:8080
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/log/nginx:/var/log/nginx
    restart: unless-stopped
    ports:
      - 9005:9125
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
